### ISSUE TITLE
method order mix-up in multimethods branch

### ISSUE THREAD

**Issue by bsumirak** [VRL-Studio/VRL#42]
Having added an object to the canvas and using several of its methods, saving and the re-opening a project will mix up the order in which the methods are represented and subsequently called.

**Comment by miho** [comment]
Does that happen with all objects or just with some of them?

**Comment by bsumirak** [comment]
This happens for all objects that call more than one method in my case.
Moreover, it seems to me that the order is always disturbed in the same way: The last method call is moved to the top, the other methods remain in order.

**Comment by miho** [comment]
I could reproduce the behavior. Here's a test project and the screenshot that shows the expected method order:

![bildschirmfoto vom 2015-02-10 19 54 53](https://cloud.githubusercontent.com/assets/225266/6134081/f4c55144-b15e-11e4-837d-d939b828ea17.png)

Sample project: https://www.dropbox.com/s/g4qeyye0ovf7txx/method-order-01.vrlp?dl=0

**Comment by bsumirak** [comment]
Works for me, too. It seems, this issue is a bit more involved.
Hmmm... Aha!
I added
    @MethodInfo(hide=false)
to the add() method.
This produced the issue.

**Comment by miho** [comment]
Seems to work now. Feel free to reopen this issue if it doesn't.
